Debug logs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -74,6 +74,7 @@ jobs:
         if: runner.os == 'Linux' && github.repository_owner == 'Open-CMSIS-Pack'
         run: |
           DESCRIBE=$(git describe --tags --long --match 'v[0-9]*.[0-9]*.[0-9]*' 2>/dev/null || true)
+          echo "DESCRIBE: ${DESCRIBE}"
           if [ -z "${DESCRIBE}" ]; then
             echo "No semver tag matching vX.Y.Z found."
             exit 1
@@ -91,16 +92,18 @@ jobs:
               ;;
             pull_request)
               npm version -s --allow-same-version --no-git-tag-version --new-version "${BASE_TAG#v}"
-              npm version --no-git-tag-version --prepatch --preid "pr${{ github.event.number }}${PR_QUALIFIER}"
+              PRERELEASE_VERSION="${BASE_TAG#v}-pr${{ github.event.number }}${PR_QUALIFIER}"
+              npm version --no-git-tag-version --new-version "${PRERELEASE_VERSION}" && echo "Prerelease version set succeeded" || echo "Prerelease version set FAILED with exit code $?"
               ;;
             *)
               npm version -s --allow-same-version --no-git-tag-version --new-version "${BASE_TAG#v}"
-              npm version --no-git-tag-version --prepatch --preid "${SAFE_REF_NAME}${BRANCH_QUALIFIER}"
+              PRERELEASE_VERSION="${BASE_TAG#v}-${SAFE_REF_NAME}${BRANCH_QUALIFIER}"
+              npm version --no-git-tag-version --new-version "${PRERELEASE_VERSION}" && echo "Prerelease version set succeeded" || echo "Prerelease version set FAILED with exit code $?"
               ;;
           esac
           VERSION="$(jq -r ".version" < package.json)"
           sed -i "s/## Unreleased/## ${VERSION}/" CHANGELOG.md
-          echo "Version is ${VERSION}"
+          echo "Updated CHANGELOG with version ${VERSION}"
 
       - name: Remove badges
         if: runner.os == 'Linux'
